export const playerTemplates = [
    {
        className: "戦士",
        hp: 100,
        mp: 30,
        physicalStrength: 50,
        magicalStrength: 15,
        attack: 35,
        defense: 15,
        speed: 20,
    },
    {
        className: "魔法使い",
        hp: 60,
        mp: 80,
        physicalStrength: 15,
        magicalStrength: 50,
        attack: 35,
        defense: 10,
        speed: 25,
    },

];

export const enemyTemplates = [
    { 
        name: "スライム",
        className: "monster", 
        hp: 100,
        mp: 0,
        attack: 40,
        physicalStrength: 40,
        magicalStrength: 0,
        defense: 15,
        speed: 20,
    },
    { 
        name: "ゴブリン",
        className: "monster", 
        hp: 100,
        mp: 30,
        attack: 40,
        physicalStrength: 30,
        magicalStrength: 10,
        defense: 20,
        speed: 20,
    },
    { 
        name: "オーク",
        className: "monster", 
        hp: 100,
        mp: 30,
        attack: 40,
        physicalStrength: 30,
        magicalStrength: 10,
        defense: 30,
        speed: 20,
    },
    { 
        name: "リッチ",
        className: "monster", 
        hp: 100,
        mp: 200,
        attack: 50,
        physicalStrength: 30,
        magicalStrength: 100,
        defense: 18,
        speed: 50,
    },
    { 
        name: "ドラゴン",
        className: "monster", 
        hp: 250,
        mp: 200,
        attack: 80,
        physicalStrength: 90,
        magicalAttack: 60,
        defense: 90,
        speed: 85,
    },
    { 
        name: "ダンジョンボス",
        className: "monster", 
        hp: 1000,
        mp: 500,
        attack: 100,
        physicalStrength: 100,
        magicalStrength: 100,
        defense: 100,
        speed: 100, 
    },
];


