// manage/templates/characterTemplates.ts

import type { EnemyTemplate } from "./characterTypes";

export const enemyTemplates: EnemyTemplate[] = [
  {
    name: "スライム",
    characterType: "monster",
    hp: 30,
    mp: 0,
    physicalStrength: 5,
    magicalStrength: 0,
    defense: 10,
    speed: 3,
  },
  {
    name: "ゴブリン",
    characterType: "monster",
    hp: 120,
    mp: 30,
    physicalStrength: 50,
    magicalStrength: 10,
    defense: 20,
    speed: 20,
  },
  {
    name: "オーク",
    characterType: "monster",
    hp: 150,
    mp: 35,
    physicalStrength: 60,
    magicalStrength: 15,
    defense: 30,
    speed: 20,
  },
  {
    name: "リッチ",
    characterType: "monster",
    hp: 300,
    mp: 200,
    physicalStrength: 70,
    magicalStrength: 100,
    defense: 18,
    speed: 50,
  },
  {
    name: "ドラゴン",
    characterType: "monster",
    hp: 500,
    mp: 200,
    physicalStrength: 80,
    magicalStrength: 70,
    defense: 80,
    speed: 50,
  },
  {
    name: "ダンジョンボス",
    characterType: "monster",
    hp: 1000,
    mp: 500,
    physicalStrength: 100,
    magicalStrength: 100,
    defense: 100,
    speed: 20,
  },
];
