export const playerTemplates = [
    {
        className: "戦士",
        hp: 130,
        mp: 30,
        physicalStrength: 50,
        magicalStrength: 15,
        defense: 25,
        speed: 20,
    },
    {
        className: "魔法使い",
        hp: 80,
        mp: 80,
        physicalStrength: 15,
        magicalStrength: 50,
        defense: 20,
        speed: 25,
    },

];

export const enemyTemplates = [
    { 
        name: "スライム",
        className: "monster", 
        hp: 100,
        mp: 0,
        physicalStrength: 40,
        magicalStrength: 0,
        defense: 15,
        speed: 20,
    },
    { 
        name: "ゴブリン",
        className: "monster", 
        hp: 120,
        mp: 30,
        physicalStrength: 50,
        magicalStrength: 10,
        defense: 20,
        speed: 20,
    },
    { 
        name: "オーク",
        className: "monster", 
        hp: 150,
        mp: 35,
        physicalStrength: 60,
        magicalStrength: 15,
        defense: 30,
        speed: 20,
    },
    { 
        name: "リッチ",
        className: "monster", 
        hp: 300,
        mp: 200,
        physicalStrength: 70,
        magicalStrength: 100,
        defense: 18,
        speed: 50,
    },
    { 
        name: "ドラゴン",
        className: "monster", 
        hp: 500,
        mp: 200,
        physicalStrength: 80,
        magicalStrength: 70,
        defense: 80,
        speed: 50,
    },
    { 
        name: "ダンジョンボス",
        className: "monster", 
        hp: 1000,
        mp: 500,
        physicalStrength: 100,
        magicalStrength: 100,
        defense: 100,
        speed: 20,
    },
];